#include "Game.hpp"


void Game::InitGameElement()
{
	left_paddle =
	{
		BASE_PADDLE_LEFT_BORDER_LEFT,
		BASE_PADDLE_LEFT_BORDER_RIGHT,
		BASE_PADDLE_TOP_BORDER,
		BASE_PADDLE_BOT_BORDER,
		BASE_PADDLE_LEFT_X,
		BASE_PADDLE_Y,
	BASE_PADDLE_WIDTH,
	BASE_PADDLE_HEIGHT,
	BASE_PADDLE_SPEED,
	};

	right_paddle = 
	{
		BASE_PADDLE_RIGHT_BORDER_LEFT,
		BASE_PADDLE_RIGHT_BORDER_RIGHT,
		BASE_PADDLE_TOP_BORDER,
		BASE_PADDLE_BOT_BORDER,
		BASE_PADDLE_RIGHT_X,
		BASE_PADDLE_Y,
	BASE_PADDLE_WIDTH,
	BASE_PADDLE_HEIGHT,
	BASE_PADDLE_SPEED,
	};

	ball = 
	{
		BASE_BALL_X,
		BASE_BALL_Y,
		0.5,
		0,
		BASE_BALL_RADIUS,
		BASE_BALL_SPEED
	};
}
